# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
- name: RuboCop Linter Action
  # You may pin to the exact commit or the version.
  # uses: andrewmcodes-archive/rubocop-linter-action@c9de2ff0e58217d3aa9167324b9dabdd2c6eefbe
  uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
  with:
    # Define a path to your optional action config file.
    action_config_path: # optional, default is .github/config/rubocop_linter_action.yml
    # Return exit code if linter returns some failures.
    exit_on_failure: # optional, default is true
